version: '3.8'

volumes:
  postgres_data:
  staticfiles:
  mediafiles:

services:
  db:
    image: postgres:13.1-alpine
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: .
    image: 02010703/yamdb:v0.23.21
    restart: always
    volumes:
      - staticfiles:/code/static
      - mediafiles:/code/media
    depends_on:
      - db
    env_file:
      - ./.env
  nginx: 
    image: nginx:1.19.5-alpine
    volumes: 
      - staticfiles:/static
      - mediafiles:/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - "80:80"
    depends_on:
      - web
    