# Generated by Django 3.0.5 on 2021-03-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.CharField(default='12345678', max_length=250),
        ),
    ]
